services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - eliza-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 5s
            timeout: 5s
            retries: 5

    eliza:
        command: ["pnpm", "start", "--character=./characters/eliza.character.json"]
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        volumes:
            - ./data:/app/data
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
            - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
            - SERVER_PORT=3000
            - TWITTER_USERNAME=${TWITTER_USERNAME}
            - TWITTER_PASSWORD=${TWITTER_PASSWORD}
            - TWITTER_EMAIL=${TWITTER_EMAIL}
            - DAEMON_PROCESS=true
        ports:
            - "3000:3000"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - eliza-network
        restart: always

    webhook:
        build:
            context: ./webhook
        environment:
            - POSTGRES_URL=${POSTGRES_URL}
            - SERVER_PORT=3030
        ports:
            - "3030:3030"
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - eliza-network
        restart: always

volumes:
    postgres_data:

networks:
    eliza-network:
        driver: bridge
